version: "3.3"
services:

  sensor:
    image: gasiepgodoy/moleculer:sensor-v1.0.12
    container_name: sensor-v1.0.12
    ports:
      - "26543:26543"
    restart: always
    environment:
      - TRANSPORTER_URL=nats://host.docker.internal:4222
      - MILLISECONDS=150
      - OPCUA_SERVER_PORT=26543
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 256m

